---
name: Setup Project
description: Setup Node.js, pnpm, and install dependencies for the portfolio project

inputs:
  node-version:
    description: Node.js version to setup
    required: false
    default: '22'
  install-dependencies:
    description: Whether to install dependencies
    required: false
    default: 'true'
  cache-key-suffix:
    description: Additional suffix for cache keys
    required: false
    default: ''

outputs:
  node-version:
    description: The Node.js version that was setup
    value: ${{ steps.setup-node.outputs.node-version }}
  cache-hit:
    description: Whether pnpm cache was hit
    value: ${{ steps.setup-pnpm.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Verify installation
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "pnpm version: $(pnpm --version)"
        echo "Dependencies installed successfully"
