onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks
  - unrs-resolver

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  tmp@<=0.2.3: '>=0.2.4'

shamefullyHoist: true
